- .github/workflows/ci.yml
- fern/fern.config.json
- fern/generators.yml
Before we can setup C# SDK generation we need to setup 
- NuGet Token
- Package Name
- CI/CD that will run `fern generate`
> 🌿 Introduce Csharp SDK generation

- asyncapi.yml
- fern/fern.config.json
- fern/generators.yml
- openapi.yml
- package.json
- Add Nano tier support:
- Add new `speech_model` field for `Transcript`, `TranscriptParams`, and `OptionalTranscriptParams`.
- Add new type `SpeechModel`
- Improve naming of `MP3` using Fern smart casing.
> Sync from internal repo (2024/02/09)

- fern/generators.yml
And move off of a dev version of the generator
> 🌿 Fix Ruby generator config to match latest schema

- fern/generators.yml
Uncommenting nuget to regenerate the alpha C# SDK
> (chore): uncomment nuget

- .gitignore
- asyncapi.yml
- fern/fern.config.json
- fern/generators.yml
- fern/openapi-overrides.yml
- openapi.yml
- Add `ForceEndUtterance` and `SetEndUtteranceSilenceThreshold` messages for real-time
- Add casing for complex enum names
> Sync from internal repo (2024/02/15)

- asyncapi.yml
- fern/generators.yml
- openapi.yml
- Add OpenAPI links where possible
- Add `transcriptWebhook` callback with a body schema `TranscriptReadyNotification`
- Specify how to format the `words` param for word search
- Specify min/max for `end_utterance_silence_threshold` field
> Sync from internal repo (2024/03/08)

- fern/docs.yml
- fern/fern.config.json
The reference is ordered like this 
```yaml
- files     
- transcripts:
- submit
- get
- getSentences
- getParagraphs
- getSubtitles
- getRedactedAudio
- wordSearch
- list
- delete
- lemur:
- task
- summary
- questionAnswer
- actionItems
- purgeRequestData
- realtime
> (feat): setup API Reference order

- .github/workflows/java-sdk.yml
This change adds a GH Workflow for releasing the Java SDK.
> Create Java Release Workflow

- README.md
- asyncapi.json
- asyncapi.yml
- fern/fern.config.json
- fern/generators.yml
- openapi.json
- openapi.yml
- package.json
- pnpm-lock.yaml
> Sync from internal repo (2024/05/30)

- fern/docs.yml
- fern/generators.yml
- openapi.yml
- Add `termsOfService`
- Add rate limiting headers
- Add `getLemurResponse` endpoint
- Add `usage` object to the LeMUR generate endpoints
> Sync from internal repo (2024/06/14)

- fern/.definition/transcripts.yml
- fern/generators.yml
- openapi.json
- openapi.yml
- Use assembly.ai URL shortener
- Remove `speaker` property that the API doesn't actually return
> Sync from internal repo (2024/10/08)

- openapi.yml
- I commented out action items temporarily - just to remove it in production for now
- final_model is a required parameter now
- removed references to deprecated models
> api-ref: LeMUR updates

- fern/pages/home.mdx
> fix: cleaned padding on banner

- fern/pages/04-lemur/ask-questions.mdx
- fern/pages/04-lemur/examples.mdx
- fern/pages/04-lemur/summarize-audio.mdx
- fern/pages/06-integrations/twilio.mdx
- Added missing Go example to Q&A with specialised endpoint
- Added C# line highlights to summary with specialised endpoint
- Added missing Go example to summary with specialised endpoint
- Added popular use cases (cookbooks) to "create custom LLM prompts" page
- Added link to Twilio Javascript SDK tutorial (cookbook) to Twilio integrations page
All changes have been locally tested.
> Dince LeMUR + Integrations Changes

- fern/docs.yml
> add playground tab

- fern/docs.yml
- fern/pages/05-guides/webhooks.mdx
- adds Migration guides sub-section to Deployments section
- updates Static IP address for webhooks info
> feat: docs updates

- fern/pages/03-audio-intelligence/summarization.mdx
- fern/pages/05-guides/transcribing-an-audio-file.mdx
In addition there are some edits to the php and ruby code on the transcribe audio page in the cookbook section: https://www.assemblyai.com/docs/guides/transcribing-an-audio-file
> docs: Add HTTP code to Audio Intelligence Summarization page

- fern/assets/custom-styles.css
- only add the sidebar styling to icons (and not the GET/POST/etc tags)
> fix: only applied sidebaricon styling to main page icons

- fern/pages/home.mdx
This adds styling on the homepage to prepare for the docs upgrade
> chore: home page styling

- fern/pages/01-getting-started/transcribe-an-audio-file.mdx
- fern/pages/01-getting-started/transcribe-an-audio-file/csharp.mdx
- fern/pages/01-getting-started/transcribe-an-audio-file/php.mdx
- fern/pages/01-getting-started/transcribe-an-audio-file/python.mdx
- fern/pages/01-getting-started/transcribe-an-audio-file/ruby.mdx
- fern/pages/01-getting-started/transcribe-an-audio-file/typescript.mdx
https://app.asana.com/0/1204255339412954/1209766351319396
> add callout for AWS file hosting

- fern/pages/01-getting-started/transcribe-an-audio-file/python.mdx
fixed indentation in python code for getting started section
> fixed indentation in python code 

- fern/pages/02-speech-to-text/universal-streaming.mdx
Added connection parameter reference.
Encoding and sample rate is required, as per [slack thread](https://assemblyai.slack.com/archives/C07V8EXGU81/p1745591865661299?thread_ts=1745591246.554549&cid=C07V8EXGU81)
> chore(usm-streaming): add param reference

- fern/pages/02-speech-to-text/universal-streaming.mdx
Removing fixed issue of final not being returned until new partial started.
> chore(usm-streaming): patch known issues

- openapi.json
- openapi.yml
@m-ods. First time making a change in API ref, so I'd appreciate you looking it over to make sure everything is ok. If not we just want to change all examples to use sonnet 3.7 instead of 3.5 (product team's request), so feel free to make you own PR if needed.
> change final model in api ref

- fern/pages/02-speech-to-text/universal-streaming.mdx
Voice agent instructions for low latency optimisation
> docs(usm-streaming): add voice agents information

- fern/docs.yml
- fern/pages/02-speech-to-text/livekit.mdx
Added Livekit page so it can be separately deployed and kept hidden as needed
> chore(usm-streaming): Livekit docs page

- fern/docs.yml
- fern/pages/02-speech-to-text/livekit.mdx
- fern/pages/02-speech-to-text/pipecat.mdx
> chore(usm-streaming): Pipecat docs page

- fern/pages/04-lemur/apply-llms-to-audio-files.mdx
- fern/pages/04-lemur/ask-questions.mdx
- fern/pages/04-lemur/customize-parameters.mdx
- fern/pages/04-lemur/examples.mdx
- fern/pages/04-lemur/summarize-audio.mdx
see: https://assemblyai.slack.com/archives/C058SSDGFDK/p1753125273696119
> fix(lemur): sonnet-4 param for python sdk examples

- fern/.definition/transcripts.yml
- openapi.json
- openapi.yml
Confirmed on slack here: https://assemblyai.slack.com/archives/C051MS5KSJJ/p1753114706079679?thread_ts=1753038670.074129&cid=C051MS5KSJJ
> Remove 10 speaker limit from speakers_expected

- fern/pages/02-speech-to-text/pre-recorded-audio/automatic-punctuation-and-casing.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/custom-spelling.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/export-paragraphs-and-sentences.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/export-srt-or-vtt-caption-files.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/filler-words.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/multichannel-transcription.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/profanity-filtering.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/speaker-diarization.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/speech-threshold.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/word-search.mdx
- fern/pages/02-speech-to-text/universal-streaming/universal-streaming.mdx
- fern/pages/03-audio-intelligence/auto-chapters.mdx
- fern/pages/03-audio-intelligence/content-moderation.mdx
- fern/pages/03-audio-intelligence/entity-detection.mdx
- fern/pages/03-audio-intelligence/key-phrases.mdx
- fern/pages/03-audio-intelligence/pii-redaction.mdx
- fern/pages/03-audio-intelligence/sentiment-analysis.mdx
- fern/pages/03-audio-intelligence/summarization.mdx
- fern/pages/03-audio-intelligence/topic-detection.mdx
- fern/pages/faq/privacy-security/does-assemblyai-offer-on-prem-deployments.mdx
- fern/pages/faq/streaming/is-streaming-stt-included-with-the-free-tier.mdx
- fern/pages/faq/streaming/upgrading-to-the-universal-streaming-model.mdx
- minor updates to the FAQs
- added supported regions/model accordion to all features
> updates: 7 aug

- fern/docs.yml
- fern/pages/05-guides/cookbooks/streaming-stt/evaluate_streaming_wer.mdx
- fern/pages/05-guides/cookbooks/streaming-stt/transcribe_audio_file.mdx
- fern/pages/05-guides/streaming.mdx
- fern/pages/faq/async/what-languages-do-you-support-.mdx
- adds WER calculation for streaming
- updates previous guide on how to stream an audio file
> misc: cookbook updates

- fern/pages/04-lemur/ask-questions.mdx
- fern/pages/04-lemur/examples.mdx
- fern/pages/04-lemur/summarize-audio.mdx
- fern/pages/08-concepts/account_management.mdx
- fern/pages/faq/accounts-billing-pricing/can-i-sign-up-for-free.mdx
- removed callouts that LeMUR is only for free tier users
- updated account managements page to reflect 2 RPM limit for free tier users using lemur
- edited the FAQ for "Can I sign up for free" (pending an edit on Pylon)
> feat: LeMUR free tier 🐈‍⬛ 

- fern/docs.yml
- fern/pages/06-integrations/index.mdx
- fern/pages/06-integrations/recall.mdx
migrating our recall guide from github to our docs
> feat: recall guide

- fern/pages/01-getting-started/models.mdx
- fern/pages/01-getting-started/supported-languages.mdx
- fern/pages/01-getting-started/transcribe-an-audio-file2.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/select-the-speech-model-with-best-and-nano.mdx
* Update model page to show Universal before Slam
* Update getting started page code examples to use Universal
* Update pre-recorded audio code examples to use Universal
* Update supported languages page to show Universal before Slam
> update resources to surface universal before slam

- fern/pages/02-speech-to-text/pre-recorded-audio/index.mdx
Remove code specifying Slam-1 as the speech model.
> remove examples showing slam-1

- fern/pages/01-getting-started/transcribe-an-audio-file2.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/index.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/select-the-speech-model-with-best-and-nano.mdx
- fern/pages/02-speech-to-text/universal-streaming/turn-detection.mdx
* Update information on disabling turn detection to present different options
* Updated getting started for pre-recorded audio to remove the specify a speech model step
* Updated pre-recorded audio code to account for how to use slam-1 and prevent errors around config object
> update turn detection info and slam-1 examples

- fern/docs.yml
- fern/pages/faq/privacy-security/what-measures-are-in-place-for-data-anonymization-or-pseudonymization.mdx
> Remove data anonymization/pseudonymization FAQ 

- fern/pages/08-concepts/account_management.mdx
- fern/pages/faq/accounts-billing-pricing/what-are-my-concurrency-limits.mdx
- fern/pages/faq/accounts-billing-pricing/what-happens-if-i-reach-my-concurrency-limit.mdx
- fern/pages/faq/streaming/how-does-automatically-scaling-concurrency-for-streaming-stt-work.mdx
Open to edits/feedback here!
[Slack thread](https://assemblyai.slack.com/archives/C07U5BAUXV0/p1752265056417339?thread_ts=1749425419.814259&cid=C07U5BAUXV0)
> Clarify streaming concurrency

- fern/docs.yml
- fern/pages/08-concepts/evals.mdx
- fern/pages/08-concepts/pre-recorded-evals.mdx
- fern/pages/08-concepts/voice-agent-evals.mdx
Add evaluation section for streaming and voice agents. Made new evaluations landing page (needs updated icons), moved pre-recorded evaluations to their own page, and new streaming/voice agents evaluations page.
> Add Evaluation section for streaming and voice agents
