- fern/fern.config.json
- fern/generators.yml
To begin generating the Ruby SDK, we are starting with generating the object models dynamically
Following soon, we will update the generator to also include the API querying and the rest of the SDK!
The Ruby SDK lives within a currently private repo: https://github.com/AssemblyAI/assemblyai-ruby-sdk
> 🌿 Introduce ruby sdk generation

- .github/workflows/ci.yml
Releases must be prefixed with `java@` and `ruby@` to target different languages.
> (chore): introduce multi-language releases like `java@1.0.1`, `ruby@0.0.1`

- fern/fern.config.json
- fern/generators.yml
As well as update the gem naming to be moved to the `output` block, mirroring the other Fern generators
> 🌿 Introduce full Ruby SDK generation

- fern/fern.config.json
Capitializing abbreviations will only be applied to Ruby (not C#/Java)
> (chore): ugprade fern to 0.17.4

- fern/fern.config.json
Previously the CLI was incorrectly parsing the `nuget` output mode.
> (chore): upgrade fern to `0.17.6` to support nuget output reading

- fern/generators.yml
This version fixes a hard dependency the Ruby generator had on a past version of the Fern CLI
> 🌿 upgrade Ruby generator to support future versions of the Fern CLI

- fern/asyncapi-overrides.yml
- fern/fern.config.json
- fern/generators.yml
- fern/openapi-overrides.yml
Now the display name for lemur is `LeMur` and for realtime it is `Streaming`.
> (feat): configure display names

- .github/workflows/csharp-sdk.yml
- fern/generators.yml
Updates generator to the correct version and sets up a github workflow trigger specifically for C#.
> (fix): setup csharp sdk generate action

- fern/generators.yml
This should address this issue: https://github.com/AssemblyAI/assemblyai-ruby-sdk/issues/31
> :herb: Bump Ruby Generator to latest

- fern/fern.config.json
This PR bumps fern's CLI version from `0.39.5` to `0.39.10`, supporting the new posthog integration.
> bumps fern's CLI version from `0.39.5` to `0.39.10`

- fern/pages/overview.mdx
This PR clarifies that rate limits are only enforced for LeMUR requests.
> docs(api): clarify that only lemur requests are rate limited

- fern/pages/overview.mdx
The correct minimum audio duration for our API is 160ms.
> fix: clarify minimum audio duration for transcription

- fern/.definition/__package__.yml
- fern/.definition/lemur.yml
- fern/.definition/realtime.yml
- fern/.definition/transcripts.yml
- fern/docs.yml
- fern/fern.config.json
- openapi.json
- openapi.yml
- package.json
- Add an example for specific HTTP error responses
- Add `multichannel` property to `TranscriptParams` and `TranscriptOptionalParams` schemas
- Add `multichannel` and `audio_channels` properties to `Transcript` schema
- Add `channel` property to `TranscriptUtterance`, `TranscriptSentence`, `TranscriptWord`, and `SentimentAnalysisResult`
- Deprecate the `dual_channel` property on the `TranscriptParams`, `TranscriptOptionalParams`, and `Transcript` schema.
- Update LeMUR examples to use latest LeMUR model instead of deprecated default model.
- Make `Error` schema have additional properties
- Update dependencies
> Sync from internal repo (2024/10/17)

- fern/docs.yml
leads to a broken link assemblyai.com/docs/overview
> revert overview page layout change

- fern/kapa.js
Use Kapa stable project image. 
There's a [PR](https://github.com/AssemblyAI/web/pull/2658) to put the project logo on https://www.assemblyai.com/static/images/logo-blue400x400.jpeg
There's a risk with using https://devrel.sandbox.assemblyai.xyz/docs/img/logo-blue400x400.jpeg whereby a new deployment to that branch will render the image route invalid since the `/docs/*` path segment is no longer managed by us.
This should not be deployed before the referenced pr hits production.
> fix(kapa): add stable project image

- fern/pages/03-audio-intelligence/auto-chapters.mdx
- fern/pages/03-audio-intelligence/sentiment-analysis.mdx
- fern/pages/03-audio-intelligence/summarization.mdx
- fern/pages/03-audio-intelligence/topic-detection.mdx
I've added Tip Boxes that include links to relevant lemur cookbooks for these audio intelligence features: topic detection, auto chapters, and sentiment analysis.
> Add lemur tips to audio intelligence pages

- fern/docs.yml
Fixes the sidebar link to the TypeScript SDK (should be `assemblyai-node-sdk`).
All other links to the TypeScript SDK use the correct URL, so no other fixes are required.
> Fix sidebar link to TypeScript SDK

- openapi.yml
- Tag the custom_topics parameter as "Depreciated" for the Transcripts endpoints
- Remove assemblyai/mistral-7b as an option for final_model for all LeMUR requests
> fix: API reference updates

- fern/pages/01-getting-started/transcribe-streaming-audio-from-a-microphone/typescript.mdx
The callback/listener for the `open` event doesn't actually create the microphone stream. In the [code example](https://www.assemblyai.com/docs/getting-started/transcribe-streaming-audio-from-a-microphone/typescript#before-you-begin), the stream is created later in the body of the main `start` function.
Relevant code from the example:
```ts
// line 16
transcriber.on('open', ({ sessionId }) => {
console.log(`Session opened with ID: ${sessionId}`)
})
...
// line 40
console.log('Connecting to real-time transcript service')
await transcriber.connect()
console.log('Starting recording')
const recording = new SoxRecording({
channels: 1,
sampleRate: SAMPLE_RATE,
audioType: 'wav' // Linear PCM
})
recording.stream().pipeTo(transcriber.stream())
``` …
> Remove open callback reference from TypeScript streaming example

- fern/pages/04-lemur/apply-llms-to-audio-files.mdx
This is a first draft PR for all HTTP code changes.
I have only changed the full code block example for this first draft, so that we can first review the code & also share it across the team to reduce duplicate work.
> docs: add HTTP code examples for apply LLMs to audio files

- fern/docs.yml
- fern/pages/01-getting-started/transcribe-an-audio-file/ruby.mdx
Questions for reviewer(s):
1. I copied the ``` comment syntax from the Python HTTP example (on this branch) for the `Or upload a local file:` snippet. It doesn't really work as a comment. Should I use the Ruby `#` comment syntax instead for that part?
2. I based the code off of [this example](https://assemblyai-preview-53dfa4e9-a646-492e-8c41-df32a5108f29.docs.buildwithfern.com/docs/speech-to-text/pre-recorded-audio/speaker-diarization). There are some things I think we can clean up here (try putting the main code snippet into Claude to get an idea), but it may be best to do all at once when the new ruby HTTP examples are fully done?
> Ruby transcribe a pre-recorded file

- cookbook-master/core-transcription/detecting-low-confidence-words.md
- fern/docs.yml
- fern/pages/02-speech-to-text/pre-recorded-audio/automatic-language-detection.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/automatic-punctuation-and-casing.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/custom-spelling.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/custom-vocabulary.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/delete-transcripts.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/export-paragraphs-and-sentences.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/export-srt-or-vtt-caption-files.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/filler-words.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/index.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/multichannel-transcription.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/profanity-filtering.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/select-the-region.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/select-the-speech-model-with-best-and-nano.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/set-language-manually.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/set-the-start-and-end-of-the-transcript.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/speaker-diarization.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/speech-threshold.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/template_codesnippet.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/transcript-status.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/word-level-timestamps.mdx
- fern/pages/02-speech-to-text/pre-recorded-audio/word-search.mdx
- fern/pages/03-audio-intelligence/key-phrases.mdx
- fern/pages/04-lemur/ask-questions.mdx
- fern/pages/04-lemur/summarize-audio.mdx
- fern/scroll-highlighted-lines.js
This PR adds functionality to automatically scroll highlighted lines into view within code blocks. When a code block contains highlighted lines (e.g., `highlight={19}`), the script will:
- Detect code blocks with highlighted lines
- Calculate the optimal scroll position to center the highlighted line
- Automatically scroll the code block's viewport to show the highlighted line
- Maintain this behavior during page loads and client-side navigation
This improves the user experience by ensuring highlighted lines are immediately visible without requiring manual scrolling, particularly useful in documentation where specific lines are referenced.
**Before:**
**After:**
> feat: scroll to highlighted lines in code blocks

- fern/docs.yml
Removed AWS marketplace URL from integrations per [this comment](https://assemblyai.slack.com/archives/C058SSDGFDK/p1743697693782579?thread_ts=1743696868.577049&cid=C058SSDGFDK) from Amy D.
> remove aws marketplace link

- fern/pages/02-speech-to-text/pre-recorded-audio/custom-spelling.mdx
* Updated the verbiage in each code block to clarify that the `to` key can only be a single word
* Update the verbiage in the alert box to include a callout that the `to` key can only be a single word
> clarify that the to key can only contain a single word

- fern/docs.yml
- fern/pages/02-speech-to-text/pre-recorded-audio/automatic-language-detection.mdx
- fern/pages/02-speech-to-text/speech-recognition.mdx
- fern/pages/06-integrations/index.mdx
- fern/pages/06-integrations/langchain/js.mdx
- fern/pages/06-integrations/power-automate.mdx
- fern/pages/06-integrations/rivet.mdx
llama integration was depreciated, so all the links were broken. I felt it would be best to remove that section from our docs.
> remove llama integration due to depreciation and some broken links

- fern/pages/01-getting-started/transcribe-an-audio-file/python.mdx
Adding /v2 to the local audio file snippet, as without this it leads to an SSL error.
> fix(docs): add missing /v2 to upload endpoint URL

- fern/pages/02-speech-to-text/streaming.mdx
Correcting the messaging in the docs to specify the expires_in parameter affects the session duration. More info in thread [here](https://assemblyai.slack.com/archives/C05S6N34ZMY/p1744649100690899).
> fix(docs): fix messaging for temp token expires_in parameter

- fern/pages/01-getting-started/models.mdx
Removed line stating Nano offers the fastest transcription speed, as it is our slowest model.
> chore(docs): adjust nano model messaging

- fern/pages/02-speech-to-text/universal-streaming.mdx
Currently utterances <240ms are not being end-pointed, leading them to become stuck as partial transcripts.
Expected to be fixed in the next model update.
> chore(usm-streaming): update known issues

- fern/pages/01-getting-started/slam-1.mdx
Adds brief clarification that Slam is only currently available on the EU endpoint. Requesting Slam on EU results in an error (telling the user to use the params `universal`, `best`, or `nano`) which is a bit confusing as I don't believe we make note of this in our docs/announcement.
> fix: clarify that Slam is only available on the US endpoint currently

- openapi.json
- openapi.yml
We are generating an API client in PHP using `openapi-generator-cli`. We noticed that the `uploadFile` endpoint/method was not usable, because it didn’t accept a file as request body. It turns out that adding a simple `schema` to the endpoint’s `requestBody` resolves this, per the example for [file uploads by Swagger](https://swagger.io/docs/specification/v3_0/describing-request-body/file-upload/).
> Add `schema` to `uploadFile` endpoint `requestBody`

- fern/pages/02-speech-to-text/streaming.mdx
The Ruby and C# Getting Started links are currently broken. They're commented out in the docs.yml file, but are still referenced in the Streaming section/lead to 404s when clicked.
> Comment out C#/Ruby guides 

- fern/pages/02-speech-to-text/universal-streaming/universal-streaming.mdx
Commented out temporary token code for now — see [this](https://assemblyai.slack.com/archives/C07V8EXGU81/p1748645836951759?thread_ts=1748008980.190369&cid=C07V8EXGU81) and [this](https://assemblyai.slack.com/archives/C07V8EXGU81/p1748650848159029?thread_ts=1748008980.190369&cid=C07V8EXGU81).
Also getting clarity on JavaScript vs TypeScript naming here, but as of now, @LeeVaughn said to keep as JavaScript for consistency.
> Add SDKs to /speech-to-text/universal-streaming

- fern/pages/01-getting-started/transcribe-streaming-audio.mdx
- fern/pages/02-speech-to-text/universal-streaming/universal-streaming.mdx
- Proper param is `formatTurns` for JS/TS.
- SDK's `transcriber` apiKey is optional if the `client` is already authed.
> Fix JS SDK for Universal-Streaming

- fern/pages/08-concepts/account_management.mdx
Correct streaming concurrency frequency from every 10 seconds to every 60 seconds.
> fix streaming concurrency scaling interval

- fern/docs.yml
- fern/pages/02-speech-to-text/universal-streaming/turn-detection.mdx
- fern/pages/02-speech-to-text/universal-streaming/universal-streaming.mdx
- fern/pages/05-guides/cookbooks/streaming-stt/transcribe_audio_file.mdx
- fern/pages/05-guides/index.mdx
- fern/pages/05-guides/streaming.mdx
- fern/pages/06-integrations/twilio.mdx
- fern/usm-streaming-overrides.yml
- usm-streaming.yml
- new cookbook: Transcribe audio files with Streaming
- removes callout for outdated Twilio/Node streaming guides
- adds default values to the API reference
- makes fixes to Streaming default values
- adds that integers in our Streaming API references refer to milliseconds
> fix(misc): Streaming fixes

- fern/pages/05-guides/cookbooks/streaming-stt/noise_reduction_streaming.mdx
- fern/pages/05-guides/streaming.mdx
The noise reduction cookbook no longer worked with the universal-streaming update:
I also updated the [Using real-time streaming](https://www.assemblyai.com/docs/guides/real-time-streaming-transcription) link to link to Universal streaming instead of legacy.
> fix streaming link and reduce noise cookbook

- fern/docs.yml
- fern/pages/02-speech-to-text/pre-recorded-audio/speaker-diarization.mdx
* Update speaker diarization page to better clarify how `speaker_options` works
* Hide old legacy streaming page
> update speaker_options verbiage and hide legacy streaming page

- fern/pages/04-lemur/customize-parameters.mdx
- openapi.yml
- adds 2 new LeMUR models to the LeMUR models page and the API reference
- marks `throttled_only` on our List endpoint as deprecated
> misc: lemur updates & api ref update

- fern/pages/02-speech-to-text/universal-streaming/universal-streaming.mdx
- streaming-token.yml
I've verified these values are correct by requesting our API directly. Use this curl command and change the values of `expires_in_seconds` and  `max_session_duration_seconds` above/below their limits. It should result in an error:
```curl
curl -G https://streaming.assemblyai.com/v3/token \
-H "Authorization: <API_KEY>" \
-d expires_in_seconds=600 \
-d max_session_duration_seconds=10800
```
> fix(streaming): temp token api reference values

- fern/docs.yml
- fern/pages/05-guides/index.mdx
Our cookbooks are not indexed by search engines the way they are hidden now so I've moved the cookbooks into the top navbar so that the sidebar in the `Documentation` section doesn't get cluttered with our many cookbooks
> feat: unhide cookbooks 🧑‍🍳 

- fern/docs.yml
- fern/pages/01-getting-started/models.mdx
- fixes a broken link for a LeMUR cookbook
- adds a redirect for common hallucinated URLs
- adds missing languages into the Fair transcription category on our supported languages page
> misc: changes on 5 sep

- fern/docs.yml
- fern/pages/02-speech-to-text/pre-recorded-audio/improving-transcript-accuracy.mdx
- fern/pages/03-audio-intelligence/pii-redaction.mdx
- fern/pages/05-guides/webhooks.mdx
- fern/pages/faq/company/what-is-your-api-uptime-sla.mdx
- fern/pages/faq/company/where-can-i-find-assemblyais-product-roadmap.mdx
- openapi.yml
* Remove prompting slam-1 page + include add redirect to the new page
* Update API reference for keyterms_prompt in GET to match POST
* add callout that the endpoint you call to get the redacted audio URL is different for NA and EU requests
* Update redact the Get redacted audio section of the API reference to reflect that this is supported for both regions
* Remove the callouts about the two webhooks calls for redacted audio
* new Pylon and Docs FAQ articles: 
* where can I see your public product roadmap?
* what is your API uptime SLA?
> misc: changes on 15 sept
